
#Se o valor nao for int ele retorna a mensagem 'except'
try:
    x = int(input('Digite um numero: '))
except:
    print('Esse numero n√£o e valido')


